// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swyipwdfrtehchuqwzwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3eWlwd2RmcnRlaGNodXF3end5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzMwNDIsImV4cCI6MjA3NDQwOTA0Mn0.-ar0IJBBT0XClrSDBU4R-Y_Xb5WY10WxMKRTVR9p0TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});